# utils/pdf_export.py

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
import io

def generate_summary_pdf(file_path, total, active, resigned,
                         mood_df=None, gender_fig=None, salary_fig=None, dept_fig=None):
    """
    Generate a PDF report with charts exactly as shown on dashboard:
    - Total, Active, Resigned employees
    - Employee Mood table (latest logs)
    - Charts: Gender, Salary, Department
    """

    doc = SimpleDocTemplate(file_path, pagesize=A4,
                            rightMargin=40, leftMargin=40, topMargin=60, bottomMargin=40)
    elements = []
    styles = getSampleStyleSheet()
    styleH = styles['Heading1']
    styleH2 = styles['Heading2']
    styleN = styles['Normal']

    # -------------------
    # Title & Summary
    # -------------------
    elements.append(Paragraph("Workforce Summary Report", styleH))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(f"<b>Total Employees:</b> {total}", styleN))
    elements.append(Paragraph(f"<b>Active Employees:</b> {active}", styleN))
    elements.append(Paragraph(f"<b>Resigned Employees:</b> {resigned}", styleN))
    elements.append(Spacer(1, 20))

    # -------------------
    # Insert Charts
    # -------------------
    def add_fig(fig, title):
        if fig is not None:
            buf = io.BytesIO()
            fig.savefig(buf, format='png', bbox_inches='tight')
            buf.seek(0)
            elements.append(Paragraph(title, styleH2))
            elements.append(Spacer(1, 10))
            elements.append(Image(buf, width=400, height=300))
            elements.append(Spacer(1, 20))

    add_fig(gender_fig, "Gender Ratio")
    add_fig(salary_fig, "Average Salary by Department")
    add_fig(dept_fig, "Department Distribution")

    # -------------------
    # Mood Table
    # -------------------
    if mood_df is not None and not mood_df.empty:
        from reportlab.platypus import Table, TableStyle
        from reportlab.lib import colors

        cols = [col for col in ["emp_id","Name","mood","log_date"] if col in mood_df.columns]
        if cols:
            mood_clean = mood_df[cols].dropna(how="all")
            if not mood_clean.empty:
                table_data = [["Emp_ID", "Name", "Mood", "Log Date"]]
                for idx, row in mood_clean.iterrows():
                    table_data.append([
                        str(row.get("emp_id","")),
                        row.get("Name",""),
                        row.get("mood",""),
                        str(row.get("log_date",""))
                    ])
                table = Table(table_data, colWidths=[60, 150, 80, 100])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
                    ('TEXTCOLOR',(0,0),(-1,0),colors.black),
                    ('ALIGN',(0,0),(-1,-1),'CENTER'),
                    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0,0), (-1,0), 12),
                    ('BOTTOMPADDING', (0,0), (-1,0), 8),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.black)
                ]))
                elements.append(Paragraph("Employee Mood (Latest Logs)", styleH2))
                elements.append(Spacer(1, 10))
                elements.append(table)

    # -------------------
    # Footer
    # -------------------
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by Workforce Analytics System", styles['Italic']))

    doc.build(elements)
