# utils/pdf_export.py

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle

def generate_summary_pdf(file_path, total, active, resigned, mood_df):
    """
    Generate a professional PDF summary:
    - total, active, resigned employees
    - Mood of employees (latest logs)
    """
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width/2, height-50, "Workforce Summary Report")

    # Summary metrics
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height-100, f"Total Employees: {total}")
    c.drawString(50, height-120, f"Active Employees: {active}")
    c.drawString(50, height-140, f"Resigned Employees: {resigned}")

    # Mood table header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height-180, "Employee Mood (Latest Logs)")

    if mood_df is not None and not mood_df.empty:
        # Ensure required columns exist
        for col in ["emp_id","Name","mood","log_date"]:
            if col not in mood_df.columns:
                mood_df[col] = "NA"

        # Prepare table data
        table_data = [["Emp_ID", "Name", "Mood", "Log Date"]]
        for _, row in mood_df.head(50).iterrows():  # only top 50 for clarity
            table_data.append([str(row["emp_id"]), row["Name"], row["mood"], str(row["log_date"])])

        # Create table
        table = Table(table_data, colWidths=[60, 150, 80, 100])
        style = TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
            ('TEXTCOLOR',(0,0),(-1,0),colors.black),
            ('ALIGN',(0,0),(-1,-1),'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 12),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black)
        ])
        table.setStyle(style)

        # Draw table
        table.wrapOn(c, width, height)
        table.drawOn(c, 50, height-450)  # adjust vertical position

    else:
        c.setFont("Helvetica", 12)
        c.drawString(50, height-200, "No mood data available.")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Workforce Analytics System")

    c.save()
